/* ═══════════════════════════════════════════════════════════════
   NOVASTORE — DATA LAYER
   Real products, real specs, real prices (2025 market prices)
═══════════════════════════════════════════════════════════════ */

const NS = window.NS || {};

NS.PRODUCTS = [
  /* ─── AUDIO ─── */
  {
    id: 1,
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    cat: 'Audio',
    sub: 'Over-Ear Headphones',
    price: 279,
    oldPrice: 349,
    rating: 4.8,
    reviews: 12847,
    stock: 34,
    sold: 2841,
    sku: 'WH1000XM5-BLK',
    badge: 'sale',
    color: '#1a1a1a',
    img: '🎧',
    imgSrc: 'assets/products/p1-sony-headphones.svg',
    imgGradient: 'linear-gradient(135deg,#1a1a1a,#2d2d2d)',
    desc: 'Industry-leading noise cancellation with Auto NC Optimizer. 30-hour battery, multipoint connection, Speak-to-Chat and Quick Attention mode.',
    specs: {
      'Driver': '30mm',
      'Frequency': '4Hz–40,000Hz',
      'Battery': '30 hours (NC on)',
      'Charge': 'USB-C, 3h full',
      'Quick Charge': '3 min → 3 hrs',
      'Weight': '250g',
      'Codec': 'SBC, AAC, LDAC',
      'Connectivity': 'Bluetooth 5.2',
      'NFC': 'Yes',
      'Microphones': '8 mics',
    },
    features: ['Industry-leading ANC', 'LDAC Hi-Res Audio', 'Multipoint dual connection', 'Quick Attention mode', 'Speak-to-Chat auto', '30hr battery life'],
    tags: ['bestseller', 'noise-cancelling', 'wireless'],
    daysLeft: 14,
  },
  {
    id: 2,
    name: 'Apple AirPods Pro (2nd Gen)',
    brand: 'Apple',
    cat: 'Audio',
    sub: 'In-Ear TWS',
    price: 199,
    oldPrice: 249,
    rating: 4.7,
    reviews: 28932,
    stock: 67,
    sold: 9241,
    sku: 'MQTP3LL/A',
    badge: 'sale',
    color: '#f5f5f7',
    img: '🎵',
    imgSrc: 'assets/products/p2-airpods.svg',
    imgGradient: 'linear-gradient(135deg,#f0f0f0,#e0e0e0)',
    desc: 'H2 chip delivers up to 2× more ANC than the previous generation. Adaptive Transparency, Personalised Spatial Audio, and MagSafe charging case.',
    specs: {
      'Chip': 'Apple H2',
      'ANC': 'Adaptive ANC',
      'Battery (buds)': '6 hours (ANC on)',
      'Battery (case)': '30 hours total',
      'Charge': 'MagSafe / Lightning / USB-C',
      'Water': 'IPX4 (buds + case)',
      'Codec': 'AAC',
      'Bluetooth': '5.3',
      'Spatial Audio': 'Personalised',
      'Find My': 'Yes',
    },
    features: ['2× stronger ANC vs Gen 1', 'Adaptive Transparency', 'Personalised Spatial Audio', 'MagSafe charging case', 'Touch controls', 'IPX4 water resistant'],
    tags: ['apple', 'airpods', 'wireless', 'anc'],
    daysLeft: 28,
  },
  {
    id: 3,
    name: 'Sennheiser HD 560S',
    brand: 'Sennheiser',
    cat: 'Audio',
    sub: 'Open-Back Headphones',
    price: 149,
    oldPrice: null,
    rating: 4.6,
    reviews: 3201,
    stock: 22,
    sold: 1102,
    sku: 'HD560S-BLK',
    badge: null,
    color: '#2a2a2a',
    img: '🎼',
    imgSrc: 'assets/products/p3-sennheiser.svg',
    imgGradient: 'linear-gradient(135deg,#2a2a2a,#404040)',
    desc: 'Analytically neutral sound signature with an open-back design for studio-grade monitoring. 120Ω impedance, wide soundstage, replaceable ear pads.',
    specs: {
      'Impedance': '120Ω',
      'Sensitivity': '110 dB SPL',
      'THD': '0.05% (1kHz / 1V)',
      'Frequency': '6Hz–38kHz',
      'Cable': '3m + 1.8m',
      'Connector': '6.35mm + 3.5mm adapter',
      'Weight': '240g',
      'Design': 'Open-back',
      'Ear pad': 'Replaceable velour',
    },
    features: ['Analytically neutral', 'Open-back design', 'Wide soundstage', 'Replaceable ear pads', 'Low THD <0.05%', 'Studio reference tuning'],
    tags: ['open-back', 'studio', 'audiophile'],
    daysLeft: 55,
  },

  /* ─── WEARABLES ─── */
  {
    id: 4,
    name: 'Apple Watch Series 10',
    brand: 'Apple',
    cat: 'Wearables',
    sub: 'Smartwatch',
    price: 399,
    oldPrice: null,
    rating: 4.9,
    reviews: 9431,
    stock: 48,
    sold: 4120,
    sku: 'MWWQ3LL/A',
    badge: 'new',
    color: '#e5e5ea',
    img: '⌚',
    imgSrc: 'assets/products/p4-apple-watch.svg',
    imgGradient: 'linear-gradient(135deg,#c8c8cc,#e5e5ea)',
    desc: 'Thinnest Apple Watch ever. S10 SiP chip, larger display, faster charging, sleep apnea detection, depth gauge, and water temperature sensor.',
    specs: {
      'Display': '46mm OLED LTPO',
      'Chip': 'S10 SiP',
      'Battery': '18 hours (36hr Low Power)',
      'Charge': '33% faster USB-C',
      'GPS': 'L1 + L5 precision',
      'Water': 'WR50 + IP6X',
      'Health': 'ECG, Blood Oxygen, Temp',
      'Sleep Apnea': 'FDA-cleared',
      'Connectivity': 'Wi-Fi 6, BT 5.3, UWB',
    },
    features: ['Sleep apnea detection (FDA)', 'Largest Apple Watch display', 'Depth gauge sensor', 'Faster USB-C charging', 'ECG + Blood Oxygen', 'watchOS 11'],
    tags: ['apple', 'smartwatch', 'health', 'fitness'],
    daysLeft: 35,
  },
  {
    id: 5,
    name: 'Samsung Galaxy Watch 7',
    brand: 'Samsung',
    cat: 'Wearables',
    sub: 'Smartwatch',
    price: 269,
    oldPrice: 299,
    rating: 4.5,
    reviews: 4820,
    stock: 41,
    sold: 2201,
    sku: 'SM-L300NZSAXAA',
    badge: 'sale',
    color: '#2d6a4f',
    img: '🕐',
    imgSrc: 'assets/products/p5-galaxy-watch.svg',
    imgGradient: 'linear-gradient(135deg,#1b4332,#2d6a4f)',
    desc: 'Exynos W1000 3nm chip — 3× faster CPU, 30% better power efficiency. Advanced AI health features: BMI body composition, advanced sleep coaching.',
    specs: {
      'Chip': 'Exynos W1000 (3nm)',
      'Display': '1.47" Super AMOLED',
      'Battery': '300mAh, ~40hr',
      'Charge': 'Wireless, 12min→10hr',
      'Sensors': 'BioActive (PPG, ECG, EDA)',
      'GPS': 'L1+L5 + GLONASS',
      'Water': '5ATM + IP68 + MIL-SPEC',
      'OS': 'Wear OS 5 / One UI 6 Watch',
    },
    features: ['3nm Exynos W1000 chip', 'Advanced AI sleep coaching', 'BMI body composition', '12min charge → 10hr use', '5ATM + IP68 + MIL-SPEC', 'Wear OS 5 / One UI 6'],
    tags: ['samsung', 'smartwatch', 'android', 'health'],
    daysLeft: 22,
  },
  {
    id: 6,
    name: 'Garmin Forerunner 965',
    brand: 'Garmin',
    cat: 'Wearables',
    sub: 'GPS Running Watch',
    price: 599,
    oldPrice: 649,
    rating: 4.8,
    reviews: 2341,
    stock: 16,
    sold: 887,
    sku: 'GRM-FR965-BLK',
    badge: null,
    color: '#1c1c2e',
    img: '🏃',
    imgSrc: 'assets/products/p6-garmin.svg',
    imgGradient: 'linear-gradient(135deg,#0f0f1a,#1c1c2e)',
    desc: 'AMOLED touchscreen, titanium bezel, multi-band GPS. Training Readiness, HRV Status, Morning Report, race predictor, recovery time advisor.',
    specs: {
      'Display': '1.4" AMOLED 454×454',
      'Battery (GPS)': 'Up to 31 hours',
      'Battery (Smartwatch)': 'Up to 23 days',
      'GPS': 'Multi-band L1/L5',
      'Bezel': 'Titanium',
      'Water': '10 ATM',
      'Maps': 'Preloaded TopoActive',
      'Music': '1,000+ songs',
      'Payments': 'Garmin Pay',
    },
    features: ['AMOLED 454×454 display', 'Multi-band L1/L5 GPS', 'Training Readiness score', 'HRV Status tracking', '31hr GPS battery', 'Preloaded topo maps'],
    tags: ['garmin', 'running', 'gps', 'triathlon', 'fitness'],
    daysLeft: 41,
  },

  /* ─── ELECTRONICS / PHONES ─── */
  {
    id: 7,
    name: 'iPhone 16 Pro Max',
    brand: 'Apple',
    cat: 'Electronics',
    sub: 'Smartphone',
    price: 1199,
    oldPrice: null,
    rating: 4.9,
    reviews: 32410,
    stock: 29,
    sold: 12831,
    sku: 'MYP83LL/A',
    badge: 'hot',
    color: '#4a3728',
    img: '📱',
    imgSrc: 'assets/products/p7-iphone.svg',
    imgGradient: 'linear-gradient(135deg,#3a2a1a,#6b4c34)',
    desc: 'A18 Pro chip with 6-core GPU. 6.9" Super Retina XDR with ProMotion. 48MP Fusion + 48MP Ultra Wide + 12MP 5× Tetra Prism. 4K 120fps Dolby Vision.',
    specs: {
      'Chip': 'A18 Pro (3nm 2nd gen)',
      'Display': '6.9" OLED, 2868×1320, 460ppi',
      'Refresh': 'ProMotion 1–120Hz',
      'Main Camera': '48MP Fusion f/1.78',
      'Ultra Wide': '48MP f/2.2 Macro',
      'Telephoto': '12MP 5× f/2.8 Tetra Prism',
      'Video': '4K 120fps Dolby Vision',
      'Storage': '256GB / 512GB / 1TB',
      'Battery': '4685mAh',
      'Charge': 'USB-C 27W + 25W MagSafe',
      'Durability': 'Ceramic Shield + Grade 5 Ti',
    },
    features: ['A18 Pro 3nm chip', '4K 120fps Dolby Vision', '5× Tetra Prism optical zoom', 'Camera Control button', 'Ceramic Shield front', 'Grade 5 titanium frame'],
    tags: ['apple', 'iphone', 'flagship', 'camera'],
    daysLeft: 18,
  },
  {
    id: 8,
    name: 'Samsung Galaxy S25 Ultra',
    brand: 'Samsung',
    cat: 'Electronics',
    sub: 'Smartphone',
    price: 1299,
    oldPrice: null,
    rating: 4.8,
    reviews: 11203,
    stock: 24,
    sold: 7842,
    sku: 'SM-S938BZKGEUB',
    badge: 'hot',
    color: '#1a1040',
    img: '🤖',
    imgSrc: 'assets/products/p8-galaxy-s25.svg',
    imgGradient: 'linear-gradient(135deg,#0d0820,#2a1a60)',
    desc: 'Snapdragon 8 Elite for Galaxy. 200MP main camera with AI-powered ProVisual Engine. Integrated S Pen, 6.9" QHD+ Dynamic AMOLED 2X.',
    specs: {
      'Chip': 'Snapdragon 8 Elite for Galaxy',
      'RAM': '12GB LPDDR5X',
      'Display': '6.9" QHD+ AMOLED 2X 120Hz',
      'Main Camera': '200MP HP9 f/1.7 OIS',
      'Telephoto 1': '10MP 3× f/2.4',
      'Telephoto 2': '50MP 5× f/3.4 OIS',
      'Ultra Wide': '50MP f/1.9',
      'S Pen': 'Built-in, 2.8ms latency',
      'Battery': '5000mAh',
      'Charge': '45W wired / 15W wireless',
      'AI': 'Galaxy AI (on-device + cloud)',
    },
    features: ['Snapdragon 8 Elite chip', '200MP AI ProVisual camera', 'Built-in S Pen (2.8ms)', 'Galaxy AI suite on-device', '45W wired fast charge', 'Titanium frame'],
    tags: ['samsung', 's-pen', 'flagship', 'android', 'camera'],
    daysLeft: 22,
  },
  {
    id: 9,
    name: 'Sony A7C II',
    brand: 'Sony',
    cat: 'Electronics',
    sub: 'Mirrorless Camera',
    price: 2199,
    oldPrice: 2499,
    rating: 4.9,
    reviews: 1842,
    stock: 11,
    sold: 441,
    sku: 'ILCE7CM2/B',
    badge: 'sale',
    color: '#1a1a1a',
    img: '📸',
    imgSrc: 'assets/products/p9-sony-camera.svg',
    imgGradient: 'linear-gradient(135deg,#111,#2a2a2a)',
    desc: 'Full-frame 33MP BSI-CMOS sensor. AI-based subject recognition AF (human, animal, vehicle, insect). 10fps RAW burst, 4K 60fps 10-bit, 5-axis IBIS.',
    specs: {
      'Sensor': '33MP Full-Frame BSI-CMOS',
      'AF Points': '759 phase-detect',
      'Burst': '10fps RAW',
      'Video': '4K 60fps 10-bit 4:2:2',
      'IBIS': '7.0-stop 5-axis',
      'Viewfinder': '2.36M-dot OLED EVF',
      'LCD': '3" 1.04M-dot vari-angle',
      'ISO': '100–51200 (exp 204800)',
      'Battery': 'NP-FZ100, ~530 shots',
      'Card': 'CFexpress A + SD UHS-II',
    },
    features: ['33MP full-frame BSI sensor', 'AI subject recognition AF', '7.0-stop 5-axis IBIS', '4K 60fps 10-bit video', 'Compact A7C body style', 'Real-time tracking'],
    tags: ['sony', 'mirrorless', 'full-frame', 'photography', 'video'],
    daysLeft: 47,
  },

  /* ─── COMPUTING ─── */
  {
    id: 10,
    name: 'Apple MacBook Air M3',
    brand: 'Apple',
    cat: 'Computing',
    sub: 'Laptop',
    price: 1099,
    oldPrice: null,
    rating: 4.9,
    reviews: 8203,
    stock: 38,
    sold: 3241,
    sku: 'MRXN3LL/A',
    badge: 'new',
    color: '#8d6b4b',
    img: '💻',
    imgSrc: 'assets/products/p10-macbook.svg',
    imgGradient: 'linear-gradient(135deg,#6b4c34,#a07850)',
    desc: 'M3 chip with 8-core CPU and 10-core GPU. 18-hour battery, fanless design, Liquid Retina display, 2× external monitor support. Midnight, Starlight, Space Grey, Silver.',
    specs: {
      'Chip': 'Apple M3',
      'CPU': '8-core',
      'GPU': '10-core',
      'Neural Engine': '16-core',
      'RAM': '8GB / 16GB / 24GB',
      'Storage': '256GB–2TB SSD',
      'Display': '15.3" Liquid Retina 2560×1664',
      'Battery': '18 hours',
      'Charge': '35W dual USB-C',
      'Ports': '2× USB-C (Thunderbolt 3) + MagSafe 3',
      'Weight': '1.51kg',
    },
    features: ['Apple M3 chip', 'Up to 18hr battery', 'Fanless silent design', '2× external displays', '15.3" Liquid Retina', 'Wi-Fi 6E + BT 5.3'],
    tags: ['apple', 'macbook', 'laptop', 'm3', 'ultrabook'],
    daysLeft: 60,
  },
  {
    id: 11,
    name: 'Keychron Q5 Pro',
    brand: 'Keychron',
    cat: 'Computing',
    sub: 'Mechanical Keyboard',
    price: 199,
    oldPrice: null,
    rating: 4.8,
    reviews: 4102,
    stock: 55,
    sold: 2108,
    sku: 'Q5P-N3-US',
    badge: null,
    color: '#2c2c2c',
    img: '⌨️',
    imgSrc: 'assets/products/p11-keychron.svg',
    imgGradient: 'linear-gradient(135deg,#1e1e1e,#3a3a3a)',
    desc: 'QMK/VIA wireless mechanical keyboard with Keychron K Pro Brown switches. Double gasket-mounted, CNC aluminium body, south-facing RGB, 2.4GHz + BT 5.1.',
    specs: {
      'Layout': '96% (100 keys)',
      'Switches': 'Keychron K Pro Brown (hot-swap)',
      'Connectivity': '2.4GHz / BT 5.1 / USB-C',
      'Firmware': 'QMK / VIA',
      'Body': 'CNC aluminium',
      'Mount': 'Double gasket',
      'Backlight': 'South-facing per-key RGB',
      'Battery': '4000mAh',
      'Polling Rate': '1000Hz (wired)',
      'Weight': '1.65kg',
    },
    features: ['QMK/VIA fully programmable', 'Double gasket mount', 'Hot-swap PCB', 'Triple-mode wireless', 'CNC aluminium body', 'South-facing RGB per key'],
    tags: ['keyboard', 'mechanical', 'qmk', 'wireless', 'gaming'],
    daysLeft: 70,
  },
  {
    id: 12,
    name: 'Anker 575 USB-C Hub',
    brand: 'Anker',
    cat: 'Computing',
    sub: 'USB-C Docking Hub',
    price: 59,
    oldPrice: 79,
    rating: 4.6,
    reviews: 6821,
    stock: 8,
    sold: 3410,
    sku: 'A8391',
    badge: 'sale',
    color: '#1a1a2e',
    img: '🔌',
    imgSrc: 'assets/products/p12-anker-hub.svg',
    imgGradient: 'linear-gradient(135deg,#0d0d1a,#1a1a2e)',
    desc: '13-in-1 USB-C hub. 4K HDMI, 4K DisplayPort, 2× USB-A 3.2, 2× USB-C 3.2, 100W USB-C PD, SD+microSD, Ethernet 1Gbps, 3.5mm audio.',
    specs: {
      'Ports': '13-in-1',
      'HDMI': '4K@60Hz',
      'DisplayPort': '4K@60Hz',
      'USB-A': '2× USB-A 3.2 Gen2 (10Gbps)',
      'USB-C': '2× USB-C 3.2 Gen2 (10Gbps)',
      'PD': '100W USB-C',
      'Storage': 'SD 4.0 + microSD',
      'Ethernet': '1Gbps RJ45',
      'Audio': '3.5mm combo jack',
      'Compatible': 'Mac, PC, iPad Pro',
    },
    features: ['13-in-1 hub', '4K HDMI + DisplayPort', '100W pass-through PD', '1Gbps Ethernet', 'SD 4.0 card reader', 'Compact aluminium body'],
    tags: ['anker', 'usb-c', 'hub', 'docking', 'macbook'],
    daysLeft: 6,
  },

  /* ─── GAMING ─── */
  {
    id: 13,
    name: 'PlayStation 5 Slim',
    brand: 'Sony',
    cat: 'Gaming',
    sub: 'Gaming Console',
    price: 449,
    oldPrice: 499,
    rating: 4.9,
    reviews: 22103,
    stock: 7,
    sold: 11204,
    sku: 'CFI-2016A01X',
    badge: 'hot',
    color: '#f8f8fa',
    img: '🎮',
    imgSrc: 'assets/products/p13-ps5.svg',
    imgGradient: 'linear-gradient(135deg,#e8e8ec,#f5f5f8)',
    desc: 'Custom AMD RDNA 2 GPU, AMD Zen 2 CPU. Up to 8K graphics, 4K@120fps, ray tracing, SSD 825GB. DualSense haptic feedback. Detachable disc drive.',
    specs: {
      'CPU': 'AMD Zen 2 8-core 3.5GHz',
      'GPU': 'AMD RDNA 2 10.3 TFLOPS',
      'RAM': '16GB GDDR6',
      'SSD': '1TB custom NVMe 5.5GB/s',
      'Resolution': 'Up to 8K',
      '4K': '4K 120fps',
      'Ray Tracing': 'Hardware RT',
      'Optical': 'Ultra HD Blu-ray (detachable)',
      'USB': '1× USB-A + 1× USB-C front, rear ports',
      'Output': 'HDMI 2.1',
    },
    features: ['4K 120fps gaming', 'Hardware ray tracing', 'DualSense haptic + trigger', '5.5GB/s NVMe SSD', 'Detachable disc drive', 'Backwards compatible PS4'],
    tags: ['sony', 'playstation', 'console', 'gaming'],
    daysLeft: 3,
  },
  {
    id: 14,
    name: 'Logitech G Pro X Superlight 2',
    brand: 'Logitech',
    cat: 'Gaming',
    sub: 'Gaming Mouse',
    price: 159,
    oldPrice: 179,
    rating: 4.8,
    reviews: 7203,
    stock: 43,
    sold: 3882,
    sku: 'G-PRO-X-SL2-W',
    badge: null,
    color: '#f0f0f0',
    img: '🖱️',
    imgSrc: 'assets/products/p14-logitech-mouse.svg',
    imgGradient: 'linear-gradient(135deg,#e0e0e0,#f5f5f5)',
    desc: 'HERO 2 25K sensor, 44,000 IPS, 500Hz polling, 95-hour battery, 60g ultralight. LIGHTSPEED wireless. Designed with esports professionals.',
    specs: {
      'Sensor': 'HERO 2 25K optical',
      'DPI': '100–25,600',
      'IPS': '44,000',
      'Acceleration': '500G',
      'Polling': '500Hz wireless / 1000Hz wired',
      'Battery': '95 hours',
      'Weight': '60g',
      'Wireless': 'LIGHTSPEED 1ms',
      'Buttons': '5 (+ scroll)',
      'Cable': 'Included USB-A passthrough',
    },
    features: ['HERO 2 25K sensor', '44,000 IPS tracking', '60g ultralight body', '95-hour battery', 'LIGHTSPEED 1ms wireless', '500Hz polling rate'],
    tags: ['logitech', 'gaming', 'mouse', 'esports', 'wireless'],
    daysLeft: 38,
  },
  {
    id: 15,
    name: 'SteelSeries Arctis Nova Pro Wireless',
    brand: 'SteelSeries',
    cat: 'Gaming',
    sub: 'Gaming Headset',
    price: 349,
    oldPrice: 399,
    rating: 4.7,
    reviews: 5421,
    stock: 19,
    sold: 2210,
    sku: '61520',
    badge: 'sale',
    color: '#1a1a1a',
    img: '🎯',
    imgSrc: 'assets/products/p15-steelseries.svg',
    imgGradient: 'linear-gradient(135deg,#111,#222)',
    desc: 'Active Noise Cancellation, dual-wireless (2.4GHz + Bluetooth), hot-swap battery system (infinite play), Hi-Res 360° Spatial Audio, ChatMix dial.',
    specs: {
      'Driver': '40mm neodymium',
      'ANC': 'Active Noise Cancellation',
      'Wireless': '2.4GHz + Bluetooth 5.0',
      'Battery': 'Hot-swap dual battery',
      'Battery Life': 'Infinite with swap system',
      'Mic': 'ClearCast Gen 2 bidirectional',
      'Spatial Audio': '360° via Sonar software',
      'ChatMix': 'Hardware dial',
      'Platform': 'PC + PlayStation + Bluetooth',
    },
    features: ['Active Noise Cancellation', 'Hot-swap infinite battery', 'Dual wireless (2.4GHz + BT)', '360° spatial audio (Sonar)', 'ClearCast Gen 2 mic', 'ChatMix hardware dial'],
    tags: ['steelseries', 'gaming', 'headset', 'anc', 'wireless'],
    daysLeft: 24,
  },

  /* ─── PHOTOGRAPHY ─── */
  {
    id: 16,
    name: 'Elgato Key Light Air',
    brand: 'Elgato',
    cat: 'Photography',
    sub: 'Studio Lighting',
    price: 79,
    oldPrice: 99,
    rating: 4.7,
    reviews: 9302,
    stock: 61,
    sold: 4102,
    sku: 'KL-AIR',
    badge: 'sale',
    color: '#f5f5f0',
    img: '💡',
    imgSrc: 'assets/products/p16-elgato.svg',
    imgGradient: 'linear-gradient(135deg,#f0ede0,#f8f5e8)',
    desc: '45W panel, 1400 lumens, 2500K–6500K colour temperature range. App + Stream Deck control. Flicker-free LED. Works via Wi-Fi — no hub needed.',
    specs: {
      'Power': '45W LED panel',
      'Brightness': '1400 lumens',
      'Colour Temp': '2500K–6500K',
      'CRI': '>95',
      'Control': 'Wi-Fi app + Stream Deck',
      'Flicker': 'Flicker-free 60Hz+',
      'Dimming': '3–100%',
      'Compatibility': 'macOS, Windows, iOS, Android',
      'Mount': 'Cold shoe + desk clamp arm',
    },
    features: ['1400 lumen output', '2500K–6500K variable', 'CRI >95 true colour', 'Wi-Fi app control', 'Stream Deck integration', 'Flicker-free LEDs'],
    tags: ['elgato', 'lighting', 'streaming', 'studio', 'photography'],
    daysLeft: 72,
  },
  {
    id: 17,
    name: 'DJI Osmo Pocket 3',
    brand: 'DJI',
    cat: 'Photography',
    sub: 'Action Camera',
    price: 519,
    oldPrice: 599,
    rating: 4.8,
    reviews: 3841,
    stock: 23,
    sold: 1620,
    sku: 'CP.OS.00000301.01',
    badge: 'sale',
    color: '#2c2c2c',
    img: '🎥',
    imgSrc: 'assets/products/p17-dji-osmo.svg',
    imgGradient: 'linear-gradient(135deg,#1a1a1a,#333)',
    desc: '1-inch CMOS sensor, 4K 120fps, 10-bit D-Log M, 3-axis gimbal stabilisation. 1.4" OLED touchscreen. ActiveTrack 6.0 subject tracking.',
    specs: {
      'Sensor': '1-inch CMOS',
      'Resolution': '4K 120fps / 4K 60fps 10-bit',
      'Colour': 'D-Log M / HLG 10-bit',
      'Gimbal': '3-axis mechanical',
      'Display': '1.4" OLED 314×556',
      'Tracking': 'ActiveTrack 6.0',
      'Stabilisation': 'RockSteady EIS',
      'Battery': '1300mAh, ~166min',
      'Charging': 'USB-C 9W',
      'Mic': '3-mic array + 3.5mm',
    },
    features: ['1-inch CMOS sensor', '4K 120fps slow-motion', '10-bit D-Log M colour', '3-axis mechanical gimbal', 'ActiveTrack 6.0', '1.4" OLED touchscreen'],
    tags: ['dji', 'camera', 'gimbal', 'vlogging', 'action'],
    daysLeft: 31,
  },
  {
    id: 18,
    name: 'Joby GorillaPod 5K Kit',
    brand: 'Joby',
    cat: 'Photography',
    sub: 'Flexible Tripod',
    price: 99,
    oldPrice: null,
    rating: 4.7,
    reviews: 12041,
    stock: 88,
    sold: 5820,
    sku: 'JB01508-BWW',
    badge: null,
    color: '#1a1a1a',
    img: '🦑',
    imgSrc: 'assets/products/p18-joby-tripod.svg',
    imgGradient: 'linear-gradient(135deg,#111,#252525)',
    desc: '5kg load capacity, flexible legs that grip any surface, built-in Arca-Swiss ball head, bubble level, included mini-tripod and carry bag. Supports mirrorless + DSLR.',
    specs: {
      'Load Capacity': '5kg (11lbs)',
      'Ball Head': 'Arca-Swiss compatible',
      'Pan': '360° rotatable',
      'Tilt': '-90° to +90°',
      'Legs': '22 flexible leg joints',
      'Material': 'ABS + TPE non-slip',
      'Weight': '504g',
      'Height': '27.5cm extended',
      'Compatible': 'All cameras up to 5kg',
    },
    features: ['5kg load capacity', 'Flexible locking legs', 'Arca-Swiss ball head', '360° pan rotation', 'Wraps any surface', 'Bubble level included'],
    tags: ['joby', 'tripod', 'photography', 'vlogging', 'flexible'],
    daysLeft: 90,
  },
];

NS.ORDERS_DATA = [
  {id:'ORD-9841',date:'Jun 28, 2025',items:[{name:'Sony WH-1000XM5',img:'🎧',imgSrc:'assets/products/p1-sony-headphones.svg',imgGradient:'linear-gradient(135deg,#1a1a1a,#2d2d2d)'},{name:'Anker 575 USB-C Hub',img:'🔌',imgSrc:'assets/products/p12-anker-hub.svg',imgGradient:'linear-gradient(135deg,#0d0d1a,#1a1a2e)'}],total:338,status:'Delivered',tracking:'1Z999AA10123456784'},
  {id:'ORD-9812',date:'Jun 15, 2025',items:[{name:'Apple AirPods Pro 2',img:'🎵',imgSrc:'assets/products/p2-airpods.svg',imgGradient:'linear-gradient(135deg,#f0f0f0,#e0e0e0)'}],total:199,status:'Delivered',tracking:'1Z999AA10123456712'},
  {id:'ORD-9790',date:'May 31, 2025',items:[{name:'Keychron Q5 Pro',img:'⌨️',imgSrc:'assets/products/p11-keychron.svg',imgGradient:'linear-gradient(135deg,#1e1e1e,#3a3a3a)'},{name:'Logitech G Pro X Superlight 2',img:'🖱️',imgSrc:'assets/products/p14-logitech-mouse.svg',imgGradient:'linear-gradient(135deg,#e0e0e0,#f5f5f5)'}],total:358,status:'Delivered',tracking:'1Z999AA10123456700'},
];

NS.ADMIN_ORDERS = [
  {id:'ORD-9841',customer:'Emily Chen',email:'emily@example.com',items:2,total:338,status:'Delivered',date:'Jun 28'},
  {id:'ORD-9840',customer:'Marcus Webb',email:'marcus@example.com',items:1,total:1299,status:'Shipped',date:'Jun 27'},
  {id:'ORD-9839',customer:'Sofia Rossi',email:'sofia@example.com',items:3,total:847,status:'Processing',date:'Jun 27'},
  {id:'ORD-9838',customer:'Jake Thompson',email:'jake@example.com',items:1,total:449,status:'Pending',date:'Jun 26'},
  {id:'ORD-9820',customer:'Aisha Johnson',email:'aisha@example.com',items:2,total:278,status:'Delivered',date:'Jun 20'},
  {id:'ORD-9801',customer:'Lena Kim',email:'lena@example.com',items:1,total:519,status:'Processing',date:'Jun 18'},
  {id:'ORD-9795',customer:'Tom Bradley',email:'tom@example.com',items:1,total:59,status:'Delivered',date:'Jun 17'},
  {id:'ORD-9780',customer:'Priya Patel',email:'priya@example.com',items:4,total:1621,status:'Shipped',date:'Jun 14'},
];

NS.CUSTOMERS = [
  {name:'Emily Chen',email:'emily@example.com',segment:'High',spent:4840,orders:18,joined:'Jan 2024',last:'Jun 28'},
  {name:'Marcus Webb',email:'marcus@example.com',segment:'High',spent:3920,orders:12,joined:'Mar 2024',last:'Jun 27'},
  {name:'Priya Patel',email:'priya@example.com',segment:'High',spent:2840,orders:9,joined:'Nov 2023',last:'Jun 14'},
  {name:'Sofia Rossi',email:'sofia@example.com',segment:'Mid',spent:847,orders:6,joined:'Apr 2024',last:'Jun 27'},
  {name:'Jake Thompson',email:'jake@example.com',segment:'Mid',spent:712,orders:5,joined:'Feb 2024',last:'Jun 26'},
  {name:'Lena Kim',email:'lena@example.com',segment:'Mid',spent:519,orders:3,joined:'May 2024',last:'Jun 18'},
  {name:'Aisha Johnson',email:'aisha@example.com',segment:'Low',spent:278,orders:2,joined:'Jun 2024',last:'Jun 20'},
  {name:'Tom Bradley',email:'tom@example.com',segment:'Low',spent:59,orders:1,joined:'Jun 2024',last:'Jun 17'},
];

NS.REVIEWS = {
  1: [{name:'Alex M.',stars:5,date:'Jun 20',text:'Best ANC headphones money can buy. Sony nailed the comfort and sound signature — punchy bass, clear mids, airy highs.',helpful:247},
      {name:'Sarah K.',stars:5,date:'Jun 14',text:'The LDAC codec makes a massive difference if you have a good source. Easily beats Bose QC45 in ANC and sound quality.',helpful:189},
      {name:'James T.',stars:4,date:'Jun 8',text:'Incredible headphones. Only giving 4 stars because the touch controls take a little getting used to.',helpful:91}],
  2: [{name:'Rachel B.',stars:5,date:'Jun 25',text:'H2 chip is a game-changer. ANC is dramatically better than Gen 1. Transparency mode sounds completely natural.',helpful:312},
      {name:'David L.',stars:5,date:'Jun 18',text:'Stem force sensor works perfectly. Love the Personalised Spatial Audio feature — genuinely impressive.',helpful:201}],
};

NS.TEAM = [
  {
    name: 'Ryan Panashe Murangariri',
    schoolId: '2023P9104060500008',
    role: 'Lead Developer & Architect',
    focus: 'Full-stack architecture, AI/BI dashboard, predictive forecasting engine',
    initials: 'RM',
    accent: 'nova',
  },
  {
    name: 'Nicholas Ambasiza Gweera',
    schoolId: '2023P9104060500012',
    role: 'Backend & Database Engineer',
    focus: 'Node.js API design, PostgreSQL schema, order & inventory systems',
    initials: 'NG',
    accent: 'cyan',
  },
  {
    name: 'Onyegiri Kenechukwu',
    schoolId: '2023P9104060500158',
    role: 'Frontend Engineer',
    focus: 'Storefront UI, cart & checkout flow, product catalog experience',
    initials: 'OK',
    accent: 'violet',
  },
  {
    name: 'Keshell Mandaza',
    schoolId: '2023P9104060500003',
    role: 'Analytics & QA Engineer',
    focus: 'Customer segmentation logic, reporting module, testing & QA',
    initials: 'KM',
    accent: 'amber',
  },
];

window.NS = NS;
